apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  components:
  - source-controller
  - kustomize-controller
  - helm-controller
  - notification-controller
  distribution:
    version: 2.x
    registry: ghcr.io/fluxcd
  sync:
    kind: GitRepository
    url: https://github.com/Nathan-Roberts123/terraform-flux-bootstrap.git
    ref: refs/heads/master
    path: clusters/development
    pullSecret: flux-system
